### ISSUE TITLE
Stable Diffusion Model never loads.

### ISSUE THREAD

**Issue by esinanturan** [andrei-zgirvaci/expo-stable-diffusion#2]
Hi and thank you for this great idea of making SD available in react-native with iOS.
I have tried to run the example you have given in the repository in my iPhone 13 Pro Max but I do not get any response from 'loadModel' method it awaits there forever no errors,warnings or whatsoever.  its stuck at loading model log 
 What am I missing ? @andrei-zgirvaci 

```
const MODEL_PATH = FileSystem.documentDirectory + "coreml-stable-diffusion-2-1";
const SAVE_PATH = FileSystem.cacheDirectory + "image.jpeg";

export default function App() {

  const loadModel = async () => {
    console.log("loading model");
    await ExpoStableDiffusion.loadModel(MODEL_PATH);
    console.log("loaded model");
  };

  const generateImage = async () => {
    console.log("generating");
    await ExpoStableDiffusion.generateImage({
      prompt: "a photo of an astronaut riding a horse on mars",
      stepCount: 25,
      savePath: SAVE_PATH,
    });
    console.log("generated");
  };

  return (
    <View style={styles.container}>
      <Text>Testing Expo Stable Diffusion</Text>

      <Button onPress={loadModel} title="Load the Model" />

      <Button onPress={generateImage} title="Generate the image" />
    </View>
  );
}

```

**Comment by andrei-zgirvaci** [comment]
Hi, thanks for opening the issue!

There was a bug regarding how the path was parsed in Swift. I believe it's related to this issue: https://github.com/andrei-zgirvaci/expo-stable-diffusion/issues/3 which should be fixed now in `0.1.2`.

Could you update the package and give it another try?

**Comment by esinanturan** [comment]
@andrei-zgirvaci  I have tried on my device (iPhone 13 Pro Max) again but still no success. Its stuck at loading the model.
I couldn't make it work on simulator too it gives this error there;
<img width="697" alt="image" src="https://github.com/andrei-zgirvaci/expo-stable-diffusion/assets/7051983/175fda74-e365-4a96-9ca7-57dc17bfa0d3">

**Comment by andrei-zgirvaci** [comment]
@esinanturan in the simulator it looks like the model actually loaded, you can see the console output saying `loaded model`.

Regarding the CoreML warning: `Failed to get the home directory when checking model path.`, you can safely ignore it.

Give it a few more minutes and you should see `Steps: 0...` being outputted in the console and the image being generated.

Try to run the app from Xcode on your iPhone 13 Pro Max and see if you get the console: `loaded model`, it might just take longer because it's running on a smaller chip than on MacBook.

I will also add a new print in the console before generating the image, to show that image is about to be generated!

**Comment by esinanturan** [comment]
@andrei-zgirvaci  On simulator I am getting the generating response and it stucks there.
As you can see simulator using 2G of ram and doing stuff i guess but not getting response.
<img width="1353" alt="image" src="https://github.com/andrei-zgirvaci/expo-stable-diffusion/assets/7051983/ffd1967f-4c8b-4bd6-bdbe-9525489341a6">

**Comment by andrei-zgirvaci** [comment]
I will mark this issue as completed for now as the described problem was fixed.

In case you encounter other issues regarding this, let me know!
